### ISSUE TITLE
[Bug]: SHAFT_Properties_cleanAllureResultsDirectoryBeforeExecution not following defined priorities. 

### ISSUE THREAD

**Issue by zanoon2020** [ShaftHQ/SHAFT_ENGINE#1204]
**Describe the bug**
cleanAllureResultsDirectoryBeforeExecution property was configured twice , in custom property file and hardcoded during execution the priority wasn't for hardcoded 

**Link to SHAFT_Engine Console logs**

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):7.3.20230707_BETA

**To Reproduce**

1. set cleanAllureResultsDirectoryBeforeExecution to false in custome property file 
2. run any test method
3. set cleanAllureResultsDirectoryBeforeExecution to true hardcoded 
4. run the same test method again
5. observe the report has the old retry 

**Expected behavior**
as per defined priorities . Hard-coded > CLI > Files > Defaults

**Comment by MohabMohie** [comment]
the allure report is created before the test run begins, and so the directory is reused already before the code reaches the line where you set this value programmatically.
hence, the correct action here is to remove the ability to set this value programmatically because it will be too late for the engine to respect it (similar to TestNG and other key setup properties)
