### ISSUE TITLE
[Bug]: Initializing 2 shaft driver in the same test doesn't work as expected

### ISSUE THREAD

**Issue by roaamagdy** [ShaftHQ/SHAFT_ENGINE#1279]
When trying to create 2 instances from shaft driver in the same test , the second driver will always override the first one.
Example to reproduce the issue:
```

SHAFT.GUI.WebDriver googleDriver= new SHAFT.GUI.WebDriver();
SHAFT.GUI.WebDriver gmailDriver= new SHAFT.GUI.WebDriver();

googleDriver.browser().navigateToURL("https://www.google.com/");
gmailDriver.browser().navigateToURL("https://gmail.com/");

System.out.println("Google Driver URL #####"+ googleDriver.browser().getCurrentURL()); --> This will print gmail URL
```

**Expected result:** Google URL should be returned

**Comment by MohabMohie** [comment]
@roaamagdy I will defer working on this issue till the next major release early January when we will upgrade SHAFT to use JDK 21.

@MahmoudElSharkawy FYI. This will require some changes to the core of the Driver factory helper class. I'm thinking of a complete re-write, splitting the class into smaller ones that are more maintainable. As well as completely removing the thread-local approach in favor of virtual threads. This should be much faster and more widely adopted since the thread-local class-level parallelization isn't really being used by anyone and is such a hassle to maintain.

**Comment by roaamagdy** [comment]
@MohabMohie it is not released yet right?
