### ISSUE TITLE
NullPointerException when invoking "com.shaft.properties.internal.Timeouts.apiSocketTimeout()"

### ISSUE THREAD

**Issue by kariemamal** [ShaftHQ/SHAFT_ENGINE#1602]

**Comment by MohabMohie** [comment]
This is currently a known issue dear.
You aren't able to setup any properties programmatically in the following case:

1. You did not do an initial test run and therefore your listeners aren't configured.
2. You did not initialize the driver instance yet.

Kindly share your code to confirm if this is a new case.

In your case since this seems to be a global configuration for you, then note that it's advised to handle global configuration by used file-based properties as per our user guide.

**Comment by MohabMohie** [comment]
closing due to lack of response. kindly feel free to reopen it if needed.
