### ISSUE TITLE
[Bug]: this function new TouchActions(driver).tap(element locator) It works very slowly.

### ISSUE THREAD

**Issue by NohairWaffarX** [ShaftHQ/SHAFT_ENGINE#1695]
i have element and i used this function new TouchActions(driver).tap(element locator)  and work correctly and click on this element but It works very slowly.

![Screenshot_3](https://github.com/user-attachments/assets/ab2f0dec-2a5c-43cc-83d9-c284d16f98f7)

**Comment by MohabMohie** [comment]
hello dear, we cannot work on it without the requested items as per the bug template.
feel free to reopen after providing the needed data. meanwhile we will attempt some blind enhancements.

**Describe the bug**

A clear and concise description of what the bug is.


**Link to SHAFT_Engine Console logs**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!


**Link to SHAFT_Engine Extent Report HTML**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.


**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]
 4. Desktop Browser (if applicable): [e.g. chrome, safari]
 5. Desktop Browser Version (if applicable): [e.g. 22]
 6. Mobile Device Name (if applicable): [e.g. iPhone6]
 7. Mobile Device OS (if applicable): [e.g. iOS8.1]
 8. Mobile Device Browser or Native App: 
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari]
 10. Mobile Device Browser Version (if applicable): [e.g. 22]


**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Expected behavior**

A clear and concise description of what you expected to happen.


**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.


**Additional context**

Add any other relevant context about the problem here.
