### ISSUE TITLE
[Bug]: when use function type in field which has value, it don't delete this value and insert new value on it as same as type append

### ISSUE THREAD

**Issue by NohairWaffarX** [ShaftHQ/SHAFT_ENGINE#1701]
**Describe the bug**

When use function type in field which has value, it don't delete this value and insert new value on it as same as type append

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Mobile Device Name (Redmi)
 7. Mobile Device OS (Android)
 8. Mobile Device Native App (WaffarX)

**To Reproduce**

1-open app
2-Login with account gnohair@gmail.com  & password::  Ng555555
3-click on menu
4-Click on cashback on gift card
5-Click on purchase gift card
6-click on amazon Egypt

**Expected behavior**

value 10 deleted and insert value 5000

**Screenshots**
![Uploading Media (2).jfif…]()

**Comment by MustafaAgamy** [comment]
Can you please provide a link for the app to download, in order to be able to investigate further?
Can you also check the broken image links?

Thank you.

**Comment by NohairWaffarX** [comment]
app waffarX on google play

**Comment by NohairWaffarX** [comment]
please this bug solved or not ? because i need it because my code stooped and i can't continue work on it
@MustafaAgamy

**Comment by NohairWaffarX** [comment]
Please, this bug fixed or not ?? I need it in my work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NohairWaffarX** [comment]
(in attachment
![Screenshot_1](https://github.com/user-attachments/assets/2bf669aa-da94-4476-b0a7-53f6f9df4730)
)

 this is actual runnable function, 
actual result , it write 105000  not 5000 so it work as type append not type  @MohabMohie

**Comment by NohairWaffarX** [comment]
i tell you all information,  actual runnable code , data , application, steps to produce issue
@MohabMohie

**Comment by MohabMohie** [comment]
Kindly add the requested information as per the bug template below (which you also get when you open a new bug).

Mainly we're looking for console logs and the html report. Without those we have nothing.



**Describe the bug**

A clear and concise description of what the bug is.


**Link to SHAFT_Engine Console logs**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ console logs, and link it here.
Do _NOT_ paste your full console logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include console logs!


**Link to SHAFT_Engine Extent Report HTML**

Create a [GIST](https://gist.github.com) which is a paste of your _full_ extent report .html file, and link it here.


**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release):
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable):
 3. Desktop OS: [e.g. iOS]
 4. Desktop Browser (if applicable): [e.g. chrome, safari]
 5. Desktop Browser Version (if applicable): [e.g. 22]
 6. Mobile Device Name (if applicable): [e.g. iPhone6]
 7. Mobile Device OS (if applicable): [e.g. iOS8.1]
 8. Mobile Device Browser or Native App: 
 9. Mobile Device Browser (if applicable): [e.g. chrome, safari]
 10. Mobile Device Browser Version (if applicable): [e.g. 22]


**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Expected behavior**

A clear and concise description of what you expected to happen.


**Screenshots**

If applicable, add screenshots, gifs, or video recordings to help explain the issue you're facing.


**Additional context**

Add any other relevant context about the problem here.
