### ISSUE TITLE
[Bug]: BrowserStack Session Name display device name instead of build name &&  Status  is  TIMED OUT aleady regardless of PASSED/FAILED.

### ISSUE THREAD

**Issue by Ashraf-Ali-gathern** [ShaftHQ/SHAFT_ENGINE#1727]
**Describe the bug**

shaft with  BrowserStack Session Name display device name instead of build name &&  Status is  TIMED OUT aleady regardless of PASSED/FAILED. 

**Link to SHAFT_Engine  Prject**

- https://drive.google.com/file/d/1KVarL9_zMkAVpNLmCzjRS_E5B5j6kJe3/view?usp=sharing

**Screenshots**

![2](https://github.com/user-attachments/assets/d79ba3f9-7930-4226-ae53-700b1c194546)

**Comment by MohabMohie** [comment]
Regarding the first issue from the post:

examining the attached project shows that there is no proper teardown for the driver.
you need to call `driver.quit();` in your `@AfterMethod` or `@AfterClass` annotation to avoid the timeout in browserstack.

Regarding the second issue:
session name is generated automatically by browserstack, SHAFT only sets the project name and build name as per this code: https://github.com/ShaftHQ/SHAFT_ENGINE/blob/4e4041b8b0c5839ec6b748960c5f92831d931c4d/src/main/java/com/shaft/driver/internal/DriverFactory/BrowserStackHelper.java#L218

if you would like to extend this behavior kindly mention exactly what you want to happen and let's discuss in a new feature request.

I'll be closing this bug for now since it's not really valid.
