### ISSUE TITLE
Mobile issue - Method not implemented exception thrown even after the action is done with no issue 

### ISSUE THREAD

**Issue by hossameldinmohamed** [ShaftHQ/SHAFT_ENGINE#649]
**Describe the bug**
When i try to do any action like click , type or anything , i always see an exception thrown in the console and it does exist in the allure report . This happen on ios & android 

**To Reproduce**
1. Run any test on ios or android 
2. Try to click or type or any action 
3. Open the allure report 
4. See thrown exceptions 

**Expected behavior**
As long as the action is done with no issue i shouldn't see any 

**Screenshots**
<img width="799" alt="Screenshot 2022-06-27 at 11 45 59 AM" src="https://user-images.githubusercontent.com/11408969/175914024-d27eb1c2-a069-4e5e-8cba-e36d80e99811.png">
**Desktop (please complete the following information):**
 - MacBook Pro

**Smartphone (please complete the following information):**
 - Device: Iphone SE , Samsung Galaxy A52 5g
 - OS: 15.5 , Android 12 

**Links to the Exceptions **
Links to the exceptions on both devices 
- https://codeshare.io/AdNn48
- https://codeshare.io/3AMvVD

**Comment by magdyheiba** [comment]
Hi @[hossameldinmohamed](https://github.com/hossameldinmohamed) Is that the same stacktrace that you faced 
If not could you please provide us the full stacktrace ? 
[stacktrace.txt](https://github.com/ShaftHQ/SHAFT_ENGINE/files/9000232/stacktrace.txt)

**Comment by hossameldinmohamed** [comment]
@magdyheiba : Yes , They are the same  .

**Comment by MohabMohie** [comment]
issue identified in this code block
<img width="763" alt="image" src="https://user-images.githubusercontent.com/19201898/176547670-ab0d2c27-5e1a-4905-a0d4-6249b3e1fd25.png">
In one of the recent engine versions, the default screenshot type was changed from viewport to fullscreen.
triggering a fullscreen screenshot doesn't work on mobile devices because they cannot scroll automatically like web devices can.
the solutions is to check for device type, and if it's not web then take a regular viewport screenshot despite the configuration.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/19201898/176548835-556201fb-8cf8-4bcc-b053-fb8b14e7d9c1.png">

this exception is thrown after every action, because that same engine version had another change to the default whenToTakeScreenshots parameter from validation points only, to always.

**Comment by MohabMohie** [comment]
PS: the issue was not identifiable without your stacktrace, thank you!
