### ISSUE TITLE
Assertion failure exception thrown for both passed and failed tests

### ISSUE THREAD

**Issue by hossameldinmohamed** [ShaftHQ/SHAFT_ENGINE#732]
**Describe the bug**
After upgrading to latest version of shaft (6.4.20221013) when i run any test i got assertion failure exception within the teardown activities regardless the status of the test if it pass or fail .

**To Reproduce**
1. Run any test you have (mobile - web - etc ) 
2. Observe the logs after the execution .

**Expected behavior**
The tear down activities should pass with no issue 

**Screenshots**
<img width="1689" alt="Screenshot 2022-10-14 at 6 47 32 PM" src="https://user-images.githubusercontent.com/11408969/195908392-dd2ad372-cc0c-4147-aee4-59bbfafcb333.png">

**Desktop (please complete the following information):**
 *  MacBook Pro

**Links to the Exception**
 * https://codeshare.io/Od43MN

**Comment by MohabMohie** [comment]
Issue root cause: dormant bug triggered issue with new logger implementation.
fix: repositioning the project structure configurator earlier in the project setup pipeline.

The fix was deployed as a hotfix to by replacing the deployed jar files, if you face this issue kindly delete this directory (or equivalent with respect to your OS) and allow the project to rebuild its maven dependencies:
 C:\Users\{USERNAME}\.m2\repository\io\github\shafthq\SHAFT_ENGINE\6.4.20221013\

Thank you @hossameldinmohamed for the early detection, kindly try the fix and give us your feedback

**Comment by hossameldinmohamed** [comment]
The fix is working perfectly & i can assure you that the performance is way better than before 🥇 

Thanks a lot @MohabMohie for your great support  💯  

P.s i love the new logging enhancements <3  

<img width="1350" alt="Screenshot 2022-10-15 at 12 08 10 AM" src="https://user-images.githubusercontent.com/11408969/195951442-39cc1e0d-4a6a-4ed2-8186-e2968a28a9aa.png">
