### ISSUE TITLE
An Exception Occured with this Message: " Element could not be scrolled into view " in Mozilla Firefox

### ISSUE THREAD

**Issue by AhmedTalaat8** [ShaftHQ/SHAFT_ENGINE#747]
The test script cannot perform an element action "Click" and throws the exception "ElementNotInteractableException" with the description : "Element could not be scrolled into view" when running in Mozilla Firefox , While the script can perform the same action in Google Chrome 

![error 1](https://user-images.githubusercontent.com/114019213/197539120-560aa652-42ee-4658-95f4-2e7792d93f68.png)
![error 2](https://user-images.githubusercontent.com/114019213/197539132-ca246eb1-2590-4898-8bc5-ce93359503bd.png)

**Comment by zanoon2020** [comment]
Can you please share screenshot for your platform flags properties file

**Comment by MohabMohie** [comment]
Element Not Interactable is thrown when an element view is obstructed by another element.

This can happen with firefox but not chrome due to a development bug. But this bug has no impact on the end user.

A workaround would be to enable "automatically click element using JavaScript" from the SHAFT configuration manager.

Please also make sure that you're using the latest Engine version.
