### ISSUE TITLE
[Enhancement] BrowserStack property file should include "Custom ID " option

### ISSUE THREAD

**Issue by hossam-elsaid** [ShaftHQ/SHAFT_ENGINE#880]
Every app upload generates a new app_url and it's automatically got deleted after 30 days then you have to upload new apk and change the app url in the script ,  To avoid that hassle BrowserStack provides Custom_ID option to specify the application under test and don’t want to modify your test scripts after every app upload

browserStack.properties file doesn't have that option so it would be great if it contains that option.

You can find more info about custom ID [HERE](https://www.browserstack.com/docs/app-automate/appium/upload-app-define-custom-id#Using_filesystem)

**Comment by MohabMohie** [comment]
Excellent point!

We actually set the custom id while uploading a new app version, but we didn't expose a way for the user to actually use it later 😅

https://github.com/ShaftHQ/SHAFT_ENGINE/blob/cccd9d8c5d05f062367ad34609f4ef3f70963b82/src/main/java/com/shaft/api/BrowserStack.java#L50

The change will be small, approximately 7-10 lines of code, if you'd like me to walk you through how you can implement it yourself, ping me via slack.

**Comment by hossameldinmohamed** [comment]
@MohabMohie  : I can see the CustomID inside the properties file but i think it's not working as expected , 

Expected Behavior : 
According to BrowserStack docs. The test will pick up the latest uploaded version to start the execution on it. We only need to add that customID .

Actual Behavior : 
If i added CustomID without adding appUrl  the session won't start at all , If i added any appUrl( from the uploaded versions -not the latest uploaded one) the session will start on that specific url even if it's not the latest uploaded one . So i will have to use both CustomID and always change the appUrl so no point form using the customID at all

**Comment by hossameldinmohamed** [comment]
@MohabMohie : Have you managed to trace the root cause of it ?

**Comment by hossameldinmohamed** [comment]
@MohabMohie  : Gentle reminder ^^
