### ISSUE TITLE
[Bug]: for strings that are retrieved at runtime, shaft is unable to compare them as strings and only compares object references

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#923]
reported by @SondosSaber

**Comment by SondosSaber** [comment]
Unfortunaelty the issue is still happening with me 
**Describe the bug**

waitForTextToChange it doesn't work properly in SHAFT version 7.1.20230227. However Text case is passed as a faulse positive


**Steps**
1- login to the portal, wait for loading indicator to disappear, wait for element to be present, get text of that element and save it into string
2- change the value of that element from drop down menu and wait for that text of the new seleceted element to be changed via using  waitForTextToChange method and save this new value into String 
3- Compare both strings and validate the both objects are not equal 

**Expected behavior**
SHAFT should get the first value and save it in a String. Then SHAFT shoudl wait for the text to be changed to get the new value. While SHAFT has issue in wait for element to be changed so the assertion should fail 

**Actual behavior**
TC is passed as shaft is comparing the refrenece of the object not the string it self so the assertions passed 

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): 7.1.20230227
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): NA
 3. Desktop OS: Windows 11
 4. Desktop Browser (if applicable):  Chrome
 5. Desktop Browser Version (if applicable): 110.0.5481.178
 6. Mobile Device Name (if applicable): NA
 7. Mobile Device OS (if applicable): NA
 8. Mobile Device Browser or Native App: NA
 9. Mobile Device Browser (if applicable): NA
 10. Mobile Device Browser Version (if applicable): NA

**Screenshots**

![image](https://user-images.githubusercontent.com/98236412/223356282-9b4d95e6-dcdf-4966-9880-8413b82ad63b.png)
![image](https://user-images.githubusercontent.com/98236412/223357252-f65ed424-b7ea-42eb-8266-f6760bb4c7af.png)
