### ISSUE TITLE
[Bug]: GIF is not working after upgrading SHAFT

### ISSUE THREAD

**Issue by abdelrahmanwael** [ShaftHQ/SHAFT_ENGINE#937]
After upgrading SHAFT version, I found that animated GIF not working in the allure report 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/15126816/223659521-6587f2a7-93a6-486d-ac03-6d748ef49493.png">

<img width="901" alt="image" src="https://user-images.githubusercontent.com/15126816/223659060-f57f3a8b-9477-4a16-838f-22a65168d2d6.png">

**Comment by MohabMohie** [comment]
Kindly note that this issue is not reproducible on my side as seen here
![d2bbcd9ba73c0ac2](https://user-images.githubusercontent.com/19201898/224473641-810ff513-f4b8-48b9-ad5e-c30b393cc711.gif)

This gif is attached in the execution report after executing [this test class](https://github.com/ShaftHQ/SHAFT_ENGINE/blob/main/src/test/java/testPackage/SHAFTWizard/Test_Wizard_GUI.java)
![image](https://user-images.githubusercontent.com/19201898/224473518-bc0cce3f-20c1-4e96-bde1-611251a538e0.png)

Kindly make sure to delete your properties directory and allow it to regenerate, then if the issue persists, kindly include the **full shaft execution logs** and feel free to reopen this issue.

You can find your full execution logs here:
![image](https://user-images.githubusercontent.com/19201898/224473622-56a1bd53-0295-466b-bea2-d5b6fa2a7a61.png)
