### ISSUE TITLE
[Bug]: Failed to instantiate remote driver instance [Appium using SHAFT]

### ISSUE THREAD

**Issue by Ahmadje** [ShaftHQ/SHAFT_ENGINE#974]
**Describe the bug**

I`m getting that error "Driver Factory Action "setRemoteDriverInstance" failed. With the following test data "Failed to instantiate remote driver instance." whenever I`m trying to run simple code to make touch actions on android emulator using SHAFT.GUI.WebDriver 

**Link to SHAFT_Engine Console logs**

https://gist.github.com/Ahmadje/b9acf9e3904686d7f6787fd47c2b6908

**Link to SHAFT_Engine Extent Report HTML**

https://gist.github.com/Ahmadje/5a43b69bc7877b77339c055b122384ab

**Environment**

 1. SHAFT_Engine version that exhibits the issue (Note: We support only the latest release): SHAFT Engine v7.1.20230321
 2. Last SHAFT_Engine version that did not exhibit the issue (if applicable): Na
 3. Desktop OS: Windows 10
 4. Desktop Browser (if applicable): Na
 5. Desktop Browser Version (if applicable):Na
 6. Mobile Device Name (if applicable): emulator-5554
 7. Mobile Device OS (if applicable): Na
 8. Mobile Device Browser or Native App: Android
 9. Mobile Device Browser (if applicable): Na
 10. Mobile Device Browser Version (if applicable): Na

**To Reproduce**

1. Make @BeforeMethod to setUp and open ur application with SHAFT.GUI.WebDriver driver
2. and make simple @Test case to make some touch actions
3. Check the error appeared in console or allure report which "Driver Factory Action "setRemoteDriverInstance" failed. With the following test data "Failed to instantiate remote driver instance.".

**Expected behavior**

After App opened successfully driver should able to perform actions on the android emulator

**Screenshots**

![image](https://user-images.githubusercontent.com/87514692/227689490-6edb78f2-1fa1-479b-a9a5-e2ad7bf44036.png)

**Additional context**

Appium 2 server is up and running and I'm on the latest version of shaft also I tried to invalidate caches of IntelliJ after deleting properties and local.m2 folders also tried to make a new project still facing the same issue, Also code runs with AndroidDriver with no issues

**Comment by MohabMohie** [comment]
after investigating, SHAFT is setting this uiautomator2 setting by default `limitXPathContextScope` you can read more about it here [appium-uiautomator2-driver#settings-api](https://github.com/appium/appium-uiautomator2-driver#settings-api)

setting it to false enables the use of relative xpaths to identify elements, which is helpful when elements cannot be identified any other way

as per this comment https://github.com/appium/appium/discussions/16513#discussioncomment-2278278 the issue you're facing is because this setting is only available on the latest appium 2 server and uiautomator 2 driver. in your stacktrace the exception message confirms that this setting is not supported in the version of uiautomator2 driver that you're using.

```
Caused by: org.openqa.selenium.InvalidArgumentException: Setting 'limitXPathContextScope' is not supported. Only the following settings are supported: [actionAcknowledgmentTimeout, allowInvisibleElements, ignoreUnimportantViews, elementResponseAttributes, enableMultiWindows, enableNotificationListener, keyInjectionDelay, scrollAcknowledgmentTimeout, shouldUseCompactResponses, waitForIdleTimeout, waitForSelectorTimeout, normalizeTagNames, shutdownOnPowerDisconnect, simpleBoundsCalculation, trackScrollEvents, wakeLockTimeout, serverPort, mjpegServerPort, mjpegServerFramerate, mjpegScalingFactor, mjpegServerScreenshotQuality, mjpegBilinearFiltering, useResourcesForOrientationDetection]
```

So, this is not a valid bug, and the solution would be to upgrade to the latest appium server `npm update appium` and the latest uiautomator2 driver `appium driver update installed --unsafe`

**Comment by Ahmadje** [comment]
@MohabMohie Really appreciate your help, I updated uiautomator2 driver and still getting the same error 
![image](https://user-images.githubusercontent.com/87514692/228113825-ce1abc4f-d68f-4e1e-b434-3facc904e2f5.png)
here`s the latest extent report: https://gist.github.com/Ahmadje/bb4c2f47873ef9dad367b80d2b3f324c
and latest exception stacktrace: https://gist.github.com/Ahmadje/7189e428fff86ba05e55fcc89eb0bb26

**Comment by MohabMohie** [comment]
@Ahmadje I removed it for now since it was never mandatory.
