### ISSUE TITLE
[Bug]: Summary not showing the correct numbers

### ISSUE THREAD

**Issue by MohabMohie** [ShaftHQ/SHAFT_ENGINE#987]
**Describe the bug**

![image](https://user-images.githubusercontent.com/19201898/227932311-3ca3e195-eaa2-4da9-ba34-f38536edc19d.png)

**Link to SHAFT_Engine Console logs**
https://github.com/ShaftHQ/SHAFT_ENGINE/actions/runs/4530517283/jobs/7979547313#step:4:10142

**Link to SHAFT_Engine Extent Report HTML**
https://github.com/ShaftHQ/SHAFT_ENGINE/suites/11827481630/artifacts/617845351

**Comment by MahmoudElSharkawy** [comment]
The test cases counter and extent report are showing the correct numbers also as in the summary (check images).. I believe the difference in number is caused by the the reruns numbers and there's only one configuration method failing.
![image](https://user-images.githubusercontent.com/46620378/227941621-b5dcc6f9-1fe9-465c-b0bc-662d46f27e96.png)
![image](https://user-images.githubusercontent.com/46620378/227941687-ad9a9ab9-4f6d-4194-a5f4-e67981d9fd4c.png)
![image](https://user-images.githubusercontent.com/46620378/227948274-46cc33f7-70d6-4df8-b1dd-787f84eb4de5.png)

**Comment by MohabMohie** [comment]
Should the failed configuration method not be reported in the summary then?
